add new demo with list/detail patch feature
jycouet/kitql pull request #94
Opened 2022-03-25 22:10 UTC by frederikhors

2022-03-26 21:04 UTC, jycouet requested changes
Hi @frederikhors , 
Thx for the PR, but I have to say that it's quite far from the Demo1 I expect to deliver to users.

Today's demo1 is far to be perfect and outdated, bu has some concept that I what to keep.

Let me know how you want to proceed.

2022-03-26 21:04 UTC, jycouet commented on examples/demo1/src/lib/kitql/kitQLClient.ts
> +import { KitQLClient } from '@kitql/client';
A graphql thing is to put in graphql folder (at least for the demo)

2022-03-26 21:04 UTC, jycouet commented on examples/demo1/tests/test.ts
> +import { expect, test } from '@playwright/test';
I guess that it's will fail

2022-03-29 16:45 UTC, closed without merging

2022-03-29 16:45 UTC, frederikhors commented
I'll do it again now.